import Head from 'next/head'
import { Box, Button, useTheme, Typography,IconButton } from '@mui/material'
import { tokens } from '../theme'
import { transactions } from '../data/data'
import {Header} from "../components/Header"
import DownloadOutlinedIcon  from '@mui/icons-material/DownloadOutlined'
import EmailIcon from "@mui/icons-material/Email"
import PointOfSaleIcon from "@mui/icons-material/PointOfSale"
import PersonAddIcon from '@mui/icons-material/PersonAdd'
import TrafficIcon from "@mui/icons-material/Traffic"
import {LineChart} from "../components/LineChart"
import { GeoChart } from "../components/GeoChart"
import { BarChart } from "../components/BarChart"
import { StatBox } from "../components/StatBox"
import { ProgressCircle } from '../components/ProgressCircle'

export default function Home() {
  const theme = useTheme()
  const colors = tokens(theme.palette.mode)
  return (
      <Box m="20px">
       <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box display='flex'  alignItems="center" justifyContent="space-between" >
         <Header title="Dashboard" subTitle="welcome to your dashboard"/>
         <Box>
          <Button 
           sx={{
             backgroundColor:colors.blueAccent[700],
             color: colors.grey[100],
             fontSize: "14px",
             fontWeight:"bold",
             padding: "1Opx 20px"
           }}
         >
           <DownloadOutlinedIcon sx={{mr:"10px"}}/>  
           Download Reports
          </Button> 
         </Box>  
        </Box>
        <Box display="grid" gridTemplateColumns="repeat(12,1fr)" gridAutoRows="140px" gap="20px">
         <Box gridColumn="span 3" backgroundColor={colors.primary[400]} display="flex" alignItems="center" justifyContents="center">
           <StatBox
             title="12.456"
             subtitle="email sent"
             progress="0.75"
             increase="+14%"
             icon={
               <EmailIcon
                 sx={{
                   color: colors.greenAccent[600],
                   fontSize: "20px"
                 }}
               />  
             }
           />
         </Box>
         <Box gridColumn="span 3" backgroundColor={colors.primary[400]} display="flex" alignItems="center" justifyContents="center">
           <StatBox
             title="431.456"
             subtitle="Sales Obtaained"
             progress="0.50"
             increase="+21%"
             icon={
               <PointOfSaleIcon
                 sx={{
                   color: colors.greenAccent[600],
                   fontSize: "26px"
                 }}
               />  
             }
           />
         </Box>
         <Box gridColumn="span 3" backgroundColor={colors.primary[400]} display="flex" alignItems="center" justifyContents="center">
           <StatBox
             title="132.456"
             subtitle="New Clients"
             progress="0.1"
             increase="+10%"
             icon={
               <PersonAddIcon
                 sx={{
                   color: colors.greenAccent[600],
                   fontSize: "26px"
                 }}
               />  
             }
           />
         </Box>
         <Box gridColumn="span 3" backgroundColor={colors.primary[400]} display="flex" alignItems="center" justifyContents="center">
           <StatBox
             title="122.456"
             subtitle="Traffic Received"
             progress="0.8"
             increase="+43%"
             icon={
               <TrafficIcon
                 sx={{
                   color: colors.greenAccent[600],
                   fontSize: "26px"
                 }}
               />  
             }
           />
         </Box>
         <Box gridColumn="span 8" gridRow="span 2" backgroundColor={colors.primary[400]} >
           <Box mt="25px" p="0 30px" display="flex" justifyContent="space-between" alignItems="center">
           <Box>
           <Typography variant="h5" fontWeight="600" color={colors.grey[100]}> 
             Revenue Generated
           </Typography>
           <Typography variant="h3" fontWeight="bold" color={colors.greenAccent[500]}>
             $222,34
           </Typography>
           </Box>
           <Box>
             <IconButton>
               <DownloadOutlinedIcon sx={{fontSize: "26px",color: colors.greenAccent[500] }}/>
             </IconButton>
           </Box>
         </Box>
         <Box height="250px" m="-20px 0 0 0 " >
           <LineChart isDashboard={true}/>
         </Box>
         </Box>
         <Box gridColumn="span 4" gridRow="span 2" backgroundColor={colors.primary[400]} overflow="auto">
           <Box display="flex" justifyContent="space-between" alignItems="center" borderBottom={`4px solid ${colors.primary[400]}`} p="15px">
           <Typography variant="h5" fontWeight="bold" color={colors.grey[100]}>
             Recent Transactions
           </Typography>
           </Box>
           {transactions.map((transaction,i)=>(
             <Box key={i}
               display="flex"
               justifyContent="space-between"
               alignItems="center"
               borderBottom = {`4px solid ${colors.primary[500]}`}
               p="15px"
             >
             <Box>
               <Typography color={colors.greenAccent[500]} variant="h5" fontWeight="600">
                 {transaction.txtId}
               </Typography>
               <Typography color={colors.grey[100]}>
                 {transaction.user}
               </Typography>
             </Box>
             <Box color={colors.grey[100]}>
               {transaction.date}
             </Box>
             <Box backgroundColor={colors.greenAccent[500]} p="5px 10px" borderRadius="4px">
               {transaction.cost}
             </Box>  
           </Box>  
                 
           ))}
         </Box>
        <Box gridColumn="span 4" gridRow="span 2" backgroundColor={colors.primary[400]} p="30px">
         <Typography variant="h5" fontWeight="600">
           Compaign
         </Typography>
         <Box display="flex" flexDirection="column" alignItems="center" mt="25px">
           <ProgressCircle size="125"/>
           <Typography variant ="h5" color={colors.greenAccent[500]} sx={{ mt: "15px" }}>
             $50 Revenue generated
           </Typography>
           <Typography>Includs extra expanditures and costs</Typography>
         </Box>
        </Box>
        <Box gridColumn="span 4" gridRow="span 2" backgroundColor={colors.primary[400]} >
         <Typography variant="h5" fontWeight="600" sx={{padding: "30px 30px 0 30px"}}>
           Sales quantity
         </Typography>
         <Box height="250px" mt="-20px">
           <BarChart isDashboard={true}/>
         </Box>
        </Box>
        <Box gridColumn="span 4" gridRow="span 2" backgroundColor={colors.primary[400]} >
         <Typography variant="h5" fontWeight="600" sx={{padding: "30px 30px 0px 30px"}}>
           Geography based traffic
         </Typography>
         <Box height="200px" >
           <GeoChart isDashboard={true}/>
         </Box>
        </Box>
        </Box>
       </Box>
     
  )
}
